# Generated by Django 4.2.6 on 2023-10-26 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VCA", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appversion",
            name="version_name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator("^\\d+\\.\\d+\\.\\d+$")
                ],
                verbose_name="Version Name",
            ),
        ),
        migrations.AlterField(
            model_name="webversion",
            name="version_name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator("^\\d+\\.\\d+\\.\\d+$")
                ],
                verbose_name="Version Name",
            ),
        ),
    ]
